services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile  # Point to your backend Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile  # Point to your frontend Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped