name: Fullstack Calculator CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BACKEND_IMAGE: calculator-backend
  FRONTEND_IMAGE: calculator-frontend
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Java for backend build
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Build backend with Maven
      - name: Build backend
        working-directory: ./backend
        run: mvn clean package

      # Set up Node.js for frontend build
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Build frontend
      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push backend image
      - name: Build and push backend image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$BACKEND_IMAGE:latest -f backend/Dockerfile .
          docker push $DOCKERHUB_USERNAME/$BACKEND_IMAGE:latest
          
          # Optional: Tag with commit SHA
          docker tag $DOCKERHUB_USERNAME/$BACKEND_IMAGE:latest $DOCKERHUB_USERNAME/$BACKEND_IMAGE:${{ github.sha }}
          docker push $DOCKERHUB_USERNAME/$BACKEND_IMAGE:${{ github.sha }}

      # Build and push frontend image
      - name: Build and push frontend image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:latest -f frontend/Dockerfile .
          docker push $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:latest
          
          # Optional: Tag with commit SHA
          docker tag $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:latest $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:${{ github.sha }}
          docker push $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:${{ github.sha }}
