name: Fullstack Calculator CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BACKEND_IMAGE: calculator-backend
  FRONTEND_IMAGE: calculator-frontend
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Backend setup and build
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build backend
        working-directory: ./backend
        run: mvn clean package

      # Frontend setup and build
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # Docker operations
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push backend image
      - name: Build backend Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$BACKEND_IMAGE:latest -f backend/Dockerfile .
          docker push $DOCKERHUB_USERNAME/$BACKEND_IMAGE:latest

      # Build and push frontend image
      - name: Build frontend Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:latest -f frontend/Dockerfile .
          docker push $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:latest