name: Fullstack Calculator CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BACKEND_IMAGE: calculator-backend
  FRONTEND_IMAGE: calculator-frontend
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Build and push backend
      - name: Build backend
        run: |
          cd backend
          mvn clean package

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$BACKEND_IMAGE:latest .
          docker push $DOCKERHUB_USERNAME/$BACKEND_IMAGE:latest

      # Build and push frontend
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Build and push frontend image
        run: |
          docker build -f frontend/Dockerfile -t $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:latest .
          docker push $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:latest