name: Fullstack Calculator CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BACKEND_IMAGE: calculator-backend
  FRONTEND_IMAGE: calculator-frontend
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend  # Default to frontend directory

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Backend setup
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Build backend
      - name: Build backend with Maven
        working-directory: ./backend
        run: mvn clean package

      # Frontend setup
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      # Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      # Build frontend
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # Docker setup
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push backend image
      - name: Build and push backend
        run: |
          docker build -t $DOCKERHUB_USERNAME/$BACKEND_IMAGE:latest -f backend/Dockerfile .
          docker push $DOCKERHUB_USERNAME/$BACKEND_IMAGE:latest

      # Build and push frontend image
      - name: Build and push frontend
        run: |
          docker build -t $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:latest -f frontend/Dockerfile .
          docker push $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:latest